firmware-qcom-sd-600eval: Skip checking for already stripped binaries
Fixes
ERROR: QA Issue: File '/lib/firmware/dsps.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/dsps.mdt' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/gss.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/gss.mdt' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/mobicore.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]

Signed-off-by: Khem Raj <raj.khem@gmail.com>

(Cherry-picked from commit 200fda483c2c70adb1e22effd3dbcd4e2be32dab)